services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qog_data
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - bigdata-net

  # Spark Master
  spark-master:
    image: apache/spark:3.5.1
    container_name: spark_master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8081:8080" # Web UI
      - "7077:7077" # Master URL
    volumes:
      - ./jars:/opt/spark/extra_jars # Compartir drivers
    networks:
      - bigdata-net

  # Spark Worker
  spark-worker:
    image: apache/spark:3.5.1
    container_name: spark_worker
    environment:
      - SPARK_MODE=worker
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    volumes:
      - ./jars:/opt/spark/extra_jars # Compartir drivers
    networks:
      - bigdata-net

  # JupyterLab con Spark (TF se instalar√° manualmente/runtime por ahora)
  jupyter-lab:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: jupyter_lab
    ports:
      - "8888:8888" # JupyterLab
      - "4040:4040" # Spark UI (Driver)
      - "8501:8501" # Streamlit Dashboard
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=bigdata2024 # Acceso fijado
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_DRIVER_HOST=jupyter_lab
    volumes:
      - .:/home/jovyan/work
    depends_on:
      - spark-master
      - postgres
    networks:
      - bigdata-net

networks:
  bigdata-net:
    driver: bridge
